logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.teletext.ecommerce: INFO

spring:
  profiles:
    active: local
  application:
    name: Teletext Backend
  threads:
    virtual:
      enabled: true
  datasource:
      url: jdbc:postgresql://localhost:5432/teletext
      username: username
      password: password
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        default_schema: teletext
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.xml
    default-schema: teletext
    contexts: dev
  #    drop-first: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://codecake.kinde.com
#          jwk-set-uri: https://codecake.kinde.com/.well-known/jwks
#          audiences: http://localhost:8080/api
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080
  servlet:
    context-path: /api/v1/
